### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by notramo** [tbrand/neph#40]
I think, the `uninstall` command should be removed.
Why? Because it is buggy, and in most cases it is unusable, and there can't be an `uninstall` job in `neph.yml`.
- if the user don't have privileges, it don't work (but it says that uninstalling was successful):
  ```
   ~/neph >>> neph uninstall
  Neph will be uninstalled ...
  Find 'neph' at /usr/bin/neph
  Are you sure you want to uninstall 'neph'? [Y/n]
  Y
  Uninstalling neph...
  Successfully uninstalled, thanks for using 'neph' so far!
   ~/neph >>> neph
  Neph is running (0.1.14) ||||||||||||||||||||||||||||||||||||||||||||||||||100%
  main [1/1] up to date
  
  Finished in 100.82ms
   ~/neph >>>            
  ```
- if the binary name is different from `neph`, it don't find it in `PATH`, but asks to remove.
- if `neph` was installed with distro package manager, it should be uninstalled that way
- if the user installed it manually, it can be found by running `which neph`, and remove manually

**Comment by notramo** [comment]
I will work on it.
What solution should I apply?
- **(preferred)** remove it and leave an instruction in the README for uninstalling *(this solution keeps the code clean - if something isn't the task of `neph`, it shouldn't can do it)*
- move it to an option, like #43 (I think this would be a quite stupid thing. Have you seen that a program can remove itself (in the UNIX world)? Because it is the job of the distro package manager, the package manager should do it.)

**Comment by tbrand** [comment]
Agreed:+1:
I also prefer former.
