### ISSUE TITLE
clean

### ISSUE THREAD

**Issue by notramo** [tbrand/neph#43]
The `clean` action should be moved to an option (`-c, --clean`).
In that way (and if #40 will be solved), the command line argument parsing could be simplified:
Insead of the specifying a job name with the `-j` option (`neph -j install`), it could be passed directly without an option: `neph install` (in the same way as `make install`)

**Comment by tbrand** [comment]
Agree :+1:

**Comment by notramo** [comment]
I will open a PR soon.

**Comment by notramo** [comment]
I will work on it.
