### ISSUE TITLE
Unable to compile neph due to missing dependency

### ISSUE THREAD

**Issue by OvermindDL1** [tbrand/neph#53]
When running `shards build` it is unable to build because it is missing libyaml, this is not part of the build instructions on the manual and it should be stated that is required to be installed system wide as it seems unable to download and use it's own dependencies.

**Comment by notramo** [comment]
The AUR package has the `libyaml` dependency.
I will look after how to add the dependency to the homebrew file.

**Comment by OvermindDL1** [comment]
> I will look after how to add the dependency to the homebrew file.

Actually what I did was clone the repo and just build it.  ^.^

Though I'm running on a debian.

Just a line in the docs of the dependency right above the compilation step would have been fine.  :-)

**Comment by notramo** [comment]
Added the line to the README. The `master` branch is protected, so the Travis test should pass before I can merge it.

**Comment by tbrand** [comment]
Hi @OvermindDL1 ! Thanks for trying neph! :smile:

**Comment by OvermindDL1** [comment]
> Hi @OvermindDL1 ! Thanks for trying neph! :smile:

Heh, that's what I used in my recent long test on the other repo.  ^.^
