### ISSUE TITLE
Move to GitLab?

### ISSUE THREAD

**Issue by notramo** [tbrand/neph#61]
@tbrand What do you think about moving this project to GitLab? It provides more powerful tools, such as diff view without MR, chat, better issue tracker, built-in CI, etc. Also it has a GitHub import tool, that can import issues, labels, projects, pull requests, etc.
I would like to develop this tool on that platform.

**Comment by tbrand** [comment]
I don't want to watch across the sites.

**Comment by waghanza** [comment]
@notramo @tbrand does gitlab provide any free CI ? https://travis-ci.com is linked to github marketplace and I do now know if **gitlab-ci** could be used in this project

**Comment by notramo** [comment]
@waghanza 
Seems like [GitLab CI supports Crystal.](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/vendor/gitlab-ci-yml/Crystal.gitlab-ci.yml)
I would like to develop on that platform.
@tbrand GitLab has email notification system, so you would be notified when I implement something.

**Comment by tbrand** [comment]
I get email by Github since I'm watching this repo.
I think we can close this issue. There is no benefit but too much lose. (For example, from the aspect of promotion. Who can reach to this repository if we develop in Githlab? I've never search repositories in it.)

**Comment by notramo** [comment]
OK.
About searching: I've moved my [Kakoune](http://kakoune.org) plugins to GitLab, and left a README in the GitHub repos that points to the new location.
