### ISSUE TITLE
Release workflow

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#73]
Hi @tbrand  @notramo ,

Followoing #68,  the release are actually created from CI `travis-ci`.

First thing is that if we want to release from CI, we **SHOULD** release for (at least) :
* OSX
* Linux
* Windows

Dropping windows support will be conter-productive as `neph` adoption,  since à lot of devs (~1/2 according stackoverflow), are using windows.

A solution could be to use an other CI (or manuel process with cross-compilation) .

Regards,

**Comment by notramo** [comment]
@waghanza Crystal don't support Windows yet.
By the way I would prefer manuall tagging, and release automatically from CI on each tag.

**Comment by waghanza** [comment]
@notramo so probably CI (deployment workflow) **SHOULD** change, when `crystal` support Windows :stuck_out_tongue: 

`travis` is more than enough for now then
