### ISSUE TITLE
Multi-jobs selection

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#74]
Hi,

It could be useful to run multiple targets (as `make` does).

Is this feature in the roadmap @notramo @tbrand ?

Regards,

**Comment by notramo** [comment]
@waghanza this wasn't in it, but it seems to be simple to implement.

**Comment by waghanza** [comment]
It will be very useful for `which_is_the_fastest`

**Comment by waghanza** [comment]
@tbrand Any update ?

**Comment by tbrand** [comment]
@waghanza https://github.com/tbrand/neph/pull/83

**Comment by tbrand** [comment]
Shipped on 0.2.9 https://github.com/tbrand/neph/releases/tag/v0.2.9
