### ISSUE TITLE
Where is the logs?

### ISSUE THREAD

**Issue by tbrand** [tbrand/neph#75]
@notramo Did you remove it? It's one of the strong point of neph.

**Comment by tbrand** [comment]
Also I lost a way to specify a running job. Where is the option.

**Comment by tbrand** [comment]
I'm very sorry that I've reverted recent codes of @notramo. That fixes remove too many attractive features for users (including me).
If you want to continue to contribute, one of the option is forking this repository.
Your commits are still in it.

That's totally my bad since I didn't check your codes so much and didn't discuss about it since I've lost the interests for this repo for a while.
Sorry again.

**Comment by notramo** [comment]
@tbrand Please wait for me to response.
**The logs are in the `.neph` directory: `.neph/job_name/{err,out}`**
**You can specify the job by `neph [job_name]`.**
**You may want to read the man page and the example file first.**

What are the other attractive features that got removed?

Please note that the wiki documents the old version still. If you don't find something that you read about in the wiki, then that doesn't mean it got removed. The manual page is up to date, but is only about command line flags. The example build file is also up to date.

**Comment by waghanza** [comment]
@tbrand What features are you talking about ?
