### ISSUE TITLE
Mutliple configuration file

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#81]
Hi @tbrand,

The configuration file in **our** _benchmarking_ **project** is very long
https://github.com/the-benchmarker/web-frameworks/blob/master/neph.yaml

It could be easier (to maintain) if this file is splitted into parts

I mean using `-f` for a `single **configuration** and `-d` for a **multiple** configuration (one per language, for example), could be clearer

What do you think ?

Regards,

**Comment by tbrand** [comment]
Does this feature https://github.com/tbrand/neph/wiki/Import-other-configurations do that?

**Comment by waghanza** [comment]
It could. Can we import via regexp / glob ?

**Comment by tbrand** [comment]
Not now. But if you want it, I could.

**Comment by waghanza** [comment]
After reflexion, I'm not it has to be done of `neph`  level. What is sure is that I need a feature like that, and I will implement it.

We have a custom use case with our benchmark, I'm not sure this feature will be necessary at `neph` level

**Comment by waghanza** [comment]
@tbrand I'm closing this since I can do other way :stuck_out_tongue_winking_eye:
