### ISSUE TITLE
Compilation issue on 0.31

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#85]
Hi @tbrand,

`neph` seems fail compiling on `v0.31.0`

https://travis-ci.com/the-benchmarker/web-frameworks/jobs/238300739#L256

Regards,

**Comment by waghanza** [comment]
Should **NOT** be a float on https://github.com/tbrand/neph/blob/a312af35983a45cea5d900b6aef222d0ccba33d7/src/neph/job/job_executor.cr#L46-L47

**Comment by tbrand** [comment]
Ops, let me see.

**Comment by tbrand** [comment]
It's fastest to send a pr to me btw. It seems 0.31.0 via brew still doesn't come up.
