### ISSUE TITLE
Having a (very) verbose mode

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#87]
Hi @tbrand,

It could be helpful to display `stdout` / `stderr` in addintion of having those **logs**.

At least it could be helpful to display some informations in the case we do not have access to **log** files (CI for example).

What do you think ?

Regards,

**Comment by waghanza** [comment]
For example, I do not know what is the cause of my trouble in https://travis-ci.com/the-benchmarker/web-frameworks/jobs/243011230, and such a mode could be useful

**Comment by tbrand** [comment]
Hi @waghanza!

Im under vacation now, so I couldnt see the details.
I will check it after a week! Or ping me then if I forget about this. lol

**Comment by tbrand** [comment]
Ops, sorry for the late reply.

As a workaround, couldn't it be realized like this?
```bash
# build and test
neph

if [ $? -ne 0 ]; then
  cat path_to_stdout_log
  cat path_to_stderr_log
  exit -1
fi
```

**Comment by waghanza** [comment]
Yeah, you're write it could.

Having a **real-time** logging in not required
